title: Prostitution in Sanfransisco
description: and the raise of the internet
sitename: Your Website
baseurl: '/one-page-wonder-jekyll'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
